config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/continue', to: 'pages#start_here'

  post '/create_account', to: 'participants#create'

  post '/login_participant', to: 'sessions#create'
  delete '/logout_participant', to: 'sessions#destroy'

  get '/login_alchemist', to: 'sessions#alchemist_login'
  post '/login_alchemist', to: 'sessions#alchemist_create'
  delete '/logout_alchemist', to: 'sessions#alchemist_destroy'

  resources :participants, only: [:index, :new, :create, :edit, :update, :show]
  resources :notifications
  resources :participant_session_trackers, only: [:index, :create]
  resources :scores, only: [:index, :create]

  resources :alchemists

end

app/models/alchemist.rb
class Alchemist < ApplicationRecord
	before_save {self.alchemist = alchemist.downcase}
	validates :alchemist, presence: true
	VALID_USERNAME_REGEX = /[a-z][+]alchemist/
	validates :alchemist, presence: true, length: { maximum: 255 },
                    format: { with: VALID_USERNAME_REGEX  },
                    uniqueness: { case_sensitive: false }

    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/participant.rb
class Participant < ApplicationRecord
	has_many :participant_session_trackers
	before_save { email.downcase! }
	validates :firstname, presence: true, length: { maximum: 50}
	validates :lastname, presence: true, length: {maximum: 55}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6}

    def Participant.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
    end

end

app/models/participant_session_tracker.rb
class ParticipantSessionTracker < ApplicationRecord
  belongs_to :participant
  validates :participant_id, presence: true
  validates :reported_session_number, presence: true
  validates :reported_session_day, presence: true
  validates :date_reported, presence: true
  validates :sessions_completed, presence: true
  validates :sessions_left, presence: true
  validates :total_study_sessions, presence: true
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :participant
end

app/controllers/alchemists_controller.rb
class AlchemistsController < ApplicationController
	def show
		@alchemist = Alchemist.find(params[:id])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	include SessionsHelper
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/participant_session_trackers_controller.rb
class ParticipantSessionTrackersController < ApplicationController
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
	def create
		@participant = Participant.new(participant_params)
		if @participant.save
			#handle saving data 
			log_in @participant
			flash[:success] = "Welcome to Your Account. Please click the various options to become familiar with the application."
			redirect_to @participant
		else 
			render 'pages/start_here'
		end
	end


	def show
		@participant = Participant.find(params[:id])
	end

	def edit
		@participant = Participant.find(params[:id])
	end

	def update
		@participant = Participant.find(params[:id])
		if @participant.update(participant_params)
			flash[:success] = "Updated your preferences"
		else 
			flash[:error] = "Unable to update"
		end

	end

	private

	def participant_params
		params.require(:participant).permit(:firstname, :lastname, :email, :password, :password_confirmation)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
		study = Participant.find_by(email: params[:session][:email].downcase)
		if study && study.authenticate(params[:session][:password])
			log_in study
			redirect_to study
		else
			flash.now[:error] = "Invalid LogIn"
			redirect_to root_url
		end
	end

	def destroy
		log_out
		redirect_to root_url
	end

	def alchemist_login
	end

	def alchemist_create
		alchemist = Alchemist.find_by(alchemist: params[:session][:alchemist].downcase)
		if alchemist && alchemist.authenticate(params[:session][:password])
			log_in_alchemist alchemist
			redirect_to alchemist
		else
			flash.now[:error] = "Invalid LogIn"
			redirect_to root_url
		end
	end

	def alchemist_destroy
		log_out_alchemist
		redirect_to root_url
	end
end

app/helpers/alchemists_helper.rb
module AlchemistsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title (page_title = '')
		base_title = "Reconditioning Alzheimer's" 
		if page_title.empty?
			base_title
		else 
			page_title + " - " + base_title
		end
	end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/participant_session_trackers_helper.rb
module ParticipantSessionTrackersHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(study)
		session[:study_id] = study.id
	end

	def current_user
		if session[:study_id]
      		@current_user ||= Participant.find_by(id: session[:study_id])
    	end
	end

	def logged_in?
		!current_user.nil?
	end 

	def log_out
		session.delete(:study_id)
		@current_user = nil
	end


	def log_in_alchemist(alchemist)
		session[:alchemist_id] = alchemist.id
	end

	def current_alchemist
		if session[:alchemist_id]
      		@current_alchemist ||= Alchemist.find_by(id: session[:alchemist_id])
    	end
    end

	def log_out_alchemist
		session.delete(:alchemist_id)
		@current_user = nil
	end
end

app/views/alchemists/_all_alchemists.html.erb
<p> all alchmists </p>

app/views/alchemists/_edit.html.erb
<p> Edit alchemist profile </p>

app/views/alchemists/_new.html.erb
<p> Create new Alchemist </p>_

app/views/alchemists/show.html.erb
<% provide(:title, "Alchemist Dashboard")%>
<div>

	<div id="alchem-options">
		<p class="alchem-dash-opts" id="alchem-dash-users"> View All Users </p>
		<p class="alchem-dash-opts" id="alchem-dash-notify"> Send Notification </p>
		<p class="alchem-dash-opts" id="alchem-dash-add"> Add Alchemist </p>
		<p class="alchem-dash-opts" id="alchem-dash-edit"> Edit Alchemist </p>
		<p class="alchem-dash-opts" id="alchem-dash-all"> View All Alchemist </p>
	</div>


</div>

app/views/layouts/_header.html.erb
<% if logged_in? %>
<%= image_tag("bgicon-01.png", :class => 'home-logo' )%>
<%= link_to "Log Out", logout_participant_path, method: :delete, :id => "logout" %>

<% else %>
<%= link_to "Reconditioning Alzheimer's", root_url, :class=>"page-headers" %>
	<%= image_tag("bgicon-01.png", :class=> 'home-logo' )%>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://fonts.googleapis.com/css?family=Nunito|Rubik" rel="stylesheet">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/notifications/_all_notifications.html.erb
<p> List all notifications </p>

app/views/notifications/_edit_notification.html.erb
<p> Edit existing notification </p>

app/views/notifications/_new_notifications.html.erb
<p> Create new Notifications </p>

app/views/pages/home.html.erb
<% provide(:title, "Home")%>
<div id="alz-home-pg">
<h3 class="sub-headers" id="home-sub-header">  The Theory and Algorithm </h3>
<div id="ab-alz-stdy">
<p> This process focuses on using thoughts as stimuli. Thoughts affect the human body and cause a response within the body. This information allows us to hypothesize that thoughts change memory capabilities of a 
	person, inducing either memory loss or recall depending on the thought stimuli that is focused.</p>

<p><strong style="color:#6DAD43">Evidence</strong> - The connection between thoughts and the body is observed when a person says or thinks 'I am afraid'. The body has a physiological response which increases adrenaline and cortisol hormones, keeping the person in a heightened state until they reverse their thoughts to ones that induce the state of calmness suchh as 'I am calm', which the body respondes to by reversing their state  and suspending the production of the stress hormones. </p>

<p><strong style="color:#DA3694">The App </strong> - The app uses a Memory Recollection Algorithim. This algorithm feeds thoughts that induce memory recollection. Following the theory that <strong style="color:#71D0F6">memory loss is a response to the thought stimuli fed to the brain when a person constantly thinks or says 'I can't remember' or 'I have a terrible memory' or 'I forget alot' or 'I can't remember anything'.</strong> Much like adopting a state of calmness after fright, we theorize that memory loss can be reversed with the correct thought impluses. </p> 

</div>



<%= link_to "START HERE",  continue_path, :id => "start-here-bttn" %>
</div> 

<a id="donate" href="https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=thelovelypractice%40gmail.com&item_name=Alzheimer%27s+Therapy&currency_code=USD&source=url
">DONATE</a>

<p><%= link_to image_tag("fb-01.png", :class => 'social-logo' ), "https://www.facebook.com/Reconditioning-Early-Alzheimers-106285797559625/?view_public_for=106285797559625"%></p>

app/views/pages/start_here.html.erb
<% provide(:title, "Start Here" )%>

<div class="app-opts" id="sign-up-participant">
	<%= render 'participants/sign_up' %>
</div>

<div class="app-opts" id="login-participant">
	<%= render 'sessions/login_participant' %>
</div>


<button class="bttn-opts" id="sign-up-bttn"> SIGN UP </button>
<button class="bttn-opts" id="login-bttn"> LOGIN </button>

app/views/participant_session_trackers/_all_participant_trackers.html.erb
<p> All Participant Session Trackers </p>

app/views/participants/_sign_up.html.erb
<div class="form-center">
<h3 class="acct-header"> CREATE YOUR ACCOUNT </h3>
<%= form_for :participant, url: create_account_path do |f| %>
<label>
<%= f.text_field :firstname,:required => true %>
<div class="label-text" > Firstname </div>
</label>

<label>
<%= f.text_field :lastname,:required => true %>
<div class="label-text" > Lastname </div>
</label>

<label>
<%= f.email_field :email,:required => true %> 
<div class="label-text" > Email </div>
</label>

<label>
<%= f.password_field :password, :required => true %>
<div class="label-text" > Password </div>
</label>

<label>
<%= f.password_field :password_confirmation, :required => true %>
<div class="label-text" > Password Confirmation </div>
</label>

<%= f.submit "BEGIN" %>
<% end %>
</div>

<div class="acct-instructions">
	<p> Please sign up to Create An Account. 
		These sessions should be completed by
		a person suffering from memory loss with an active
		Alzheimer's Diagnosis. </p>
	<p> If you are a caregiver creating an 
		account on their behalf, please keep in mind
		that they are expected to independently complete the sessions. 
		It's is important that they do 
		this without your help.
	</p>

	<p> Please click SIGNUP to create the account or LOGIN to sign into your 
	account. </p>
</div>

app/views/participants/show.html.erb
<% provide(:title, "Dashboard")%>
<div class="alz-dashboard">
	<h3 style="position:fixed; top: 75px; left: 15px; font-size: 2.0em;color: #604677;"> Hello <%= @participant.firstname %>, </h3>

	<div id="notification-bar">
		<p class="notifications-parag"> Notifications </p>
	</div>

	<div id="options">
		<p class="dash-opts" id="dash-tips"> Start Session </p>
		<p class="dash-opts" id="dash-up-diag"> Memory Assessment Exercise </p>
		<p class="dash-opts" id="dash-htw"> How It Works </p>
	</div>

	<div id="main">
			<div class="main-opts" id="hello_user">
				<div>
					<h3 class="hiw-headers"> On NOTIFICATIONS </h3 >
					<p> Use the notification tab above to track any reminders.  </p>
				</div>

				<div>
					<h3 class="hiw-headers"> On DAILY SESSIONS</h3 >
					<p> Click <strong>'Start Session'</strong> to begin today's session. <p>
				</div>

				<div>
					<h3 class="hiw-headers"> On MEMORY ASSESSMENT EXERCISES </h3 >
					<p> <%= @participant.firstname%>, You are encouraged to take as many Memory Assessment Exercises as possible, in addition to the Mandatory Weekly Assessment.  
					</p>

					<p> Click the Memory Assessment Exercise Option located right of the screen. </p>
				</div>

			</div>


		<div class="main-opts" id="hItW">
			<%= render 'shared/how_it_works' %>
		</div>

		<div class="main-opts" id="upload-diag">
			<%= render 'shared/mem_assess' %>
		</div>

		<div class="main-opts" id="session">
			<div class="memory_sesh" id="start_algorithm">
				<p id="intro-counter">0 / 25</p>
				<p class="session-instruction">Click the sentence below and type it 25 times, before proceeding to the daily session. </p>
				<textarea class="mantras" id="bg_mantra" readonly>I love using this app everyday</textarea>
				<textarea class="mantras" id="type_mantra"> </textarea>
				<p class="mini-mantra"> Type the sentence below 25 times in the space above... <br> I love using this app everyday </p>
			</div>

			<div class="memory_sesh" id="start_memory_session">
				<p style="color: #604677; text-align: center; font-size: 1.3em;">
					Welcome to your Memory Recollection Session. Click the button to get started.
				</p>
				<button id="begin-session"> BEGIN </button>
			</div>

			<div class="memory_sesh" id="memory_recall">
				<p style="color: #E1A13E; font-size: 2.5em; text-align: center;" id="memory-counter">0 / 250</p>
				<p class="session-instruction"><strong style="color: #C23F97; font-size: 2.0em;">" I love my memory. It's the best. I always clearly remember everything. I am not forgetful."</strong> Click below and type this sentence 250 times. </p>
				<textarea style="height: 450px;" class="mantras" id="bg_memory" readonly>I love my memory. It's the best. I always clearly remember everything. I am not forgetful.</textarea>
				<textarea style="height: 450px;" class="mantras" id="type_memory"> </textarea>
				<p  class="m-mantra"> Type the sentence below 250 times in the space above... <br> I love my memory. It's the best. I always clearly remember everything. I am not forgetful. </p>
			</div>

		</div>

	</div>



	<div id="progress-bar">
		<p style="text-align: center; font-size: 1.5em; color: #C23F97;"> CURRENT PROGRESS </p>
		<p style="text-align: center; color: #E1A13E;"> Number of Sessions Completed / Number of Sessions Left </p>
		<progress value="22" max="100"> </progress>
	</div>

</div>

app/views/shared/_error_message.html.erb
<% if @participant.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@participant.errors.count, "error") %>.
    </div>
    <ul>
    <% @participant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_how_it_works.html.erb
<div class="hiw-content">
	<h3 class="hiw-headers"> Thoughts Control Body Pathways </h3 >
	<p class="hiw-parag">The study is based on the hypothesis that Thoughts are stimuli that trigger correspponding responses in the human body.</p>
	<p class="hiw-parag"> We hypothesize that Thoughts can trigger pathway responses which go back to the gene and reset the  constitution of the particular pathway. </p>

</div>

<div  class="hiw-content">
	<h3 class="hiw-headers"> Thoughts Become Things </h3 >
	<p class="hiw-parag"> The study would  like to demonstrate that engaging correct Thoughts can trigger memory recall and reverse memory loss. </p>
	<p class="hiw-parag"> This is based on the  hypothesis that each thought encodes a pathway in the human body that causes a corresponding action. </p>

</div>

<div class="hiw-content">
	<h3 class="hiw-headers"> Daily Sessions </h3>
	<p class="hiw-parag"> The participant is expected to take part in a Daily Session everyday. </p class="hiw-parag">
	<p class="hiw-parag"> These sessions are designed to encode appropriate Thought stimuli, that engages memory recall. </p>
	<p class="hiw-parag"> It is important that the participants perform these daily sessions, which are tracked for data collection. </p>
</div>

<div class="hiw-content">
	<h3 class="hiw-headers"> Weekly Memory Assessment </h3>
	<p class="hiw-parag"> Participants are presented with a scored memory assessment exercise every 7 days. </p class="hiw-parag">
	<p class="hiw-parag"> The Memory Assessment Exercises are designed to track the participants memory improvement over the course of the study. </p>
	<p class="hiw-parag"> Please ensure that you complete the exercises. </p>

	</div>

app/views/shared/_mem_assess.html.erb
<div id="quiz_count"> 
<p class="hiw-headers"> Total Number of Quizzes taken </p>
<div id="total_quizzes">
	<p>15</p>
</div>
</div>

<div id="images">
	<%= image_tag("rabbithat-01.png", :class => 'memory_imgs test-imgs' )%>
	<%= image_tag("ladybug-01.png", :class => 'memory_imgs test-imgs' )%>
	<%= image_tag("board-01.png", :class => 'memory_imgs test-imgs ' )%>
	<%= image_tag("space-01.png", :class => 'memory_imgs test-imgs' )%>
	<%= image_tag("boxes-01.png", :class => 'memory_imgs test-imgs' )%>
	<%= image_tag("futbol-01.png", :class => 'memory_imgs test-imgs' )%>
	<%= image_tag("gas-01.png", :class => 'memory_imgs test-imgs' )%>
	<%= image_tag("pengiun-01.png", :class => 'memory_imgs test-imgs' )%>
	<%= image_tag("letter-01.png", :class => 'memory_imgs test-imgs' )%>
	<%= image_tag("balloon-01.png", :class => 'memory_imgs test-imgs' )%>
	<%= image_tag("books-01.png", :class => 'memory_imgs test-imgs' )%>
	<%= image_tag("painter-01.png", :class => 'memory_imgs test-imgs' )%>
	<%= image_tag("whale-01.png", :class => 'memory_imgs test-imgs' )%>
	<%= image_tag("school-01.png", :class => 'memory_imgs test-imgs' )%>
	<div id="mem_instructions"> 
		<h1 class="hiw-headers"> Instructions </h1>
		<p> The Memory Assessment Exercises can be taken as frequently as the user prefers BUT</p>
		<p> every user is required to take a weekly exercise requirement. This exercise allows the user to track the effectiveness of the mind coaching and memory recollection exercises. It is impertive that the user take satisfy all the application's process to greatly benefit from this process. </p>
		<h3 class="sub-headers" > How the Recollection Quizzes Work </h3>
		<ol> .Each quiz has 6 questions that present the user with 5 images.  </ol>
		<ol> .The user must select an image for each question. </ol>
		<ol> .This image and all other images are faded for a randomized length of time. </ol>
		<ol> .Once the recall time expires, the user is presented with a set of 6 images and must select the image they remember selecting. </ol>
		<ol> .The user's progress at selecting the correct images is tracked by the application. </ol> 
	</div>
</div>

<div class="memory_assess" id="tutorial">
	<%= image_tag("rabbithat-01.png", :id => 'imgOne', :class => 'tut' )%>
	<%= image_tag("balloon-01.png", :id => 'imgTwo', :class => 'tut'  )%>
	<%= image_tag("whale-01.png", :id => 'imgThree', :class => 'tut'  )%>
	<%= image_tag("ladybug-01.png", :id => 'imgFour', :class => 'tut'  )%>
	<%= image_tag("gas-01.png", :id => 'imgFive', :class => 'tut'  )%>

	<p style="text-align:center; font-size: 2.0em; font-family: 'Nunito', sans-serif; color: #0095DA;
" id="quiz-instruct"></p>
</div>

<div class="rememberal">
	<p id="type-remember"> </p>
	<p id="remember-time"> </p>
</div>

<div class="memory_assess" id="exercise">
	<p> Welcome to the memory assessment exercise </p>
</div>

<button class="mem_bttn" id="start_tutorial"> TUTORIAL </button>
<button class="mem_bttn" id="start_assessment"> BEGIN ASSESSMENT </button>